#!/usr/bin/env bash
#PBS -q condo
#PBS -N Amiga_h553_spec
#PBS -l walltime=8:00:00
#PBS -l nodes=1:ppn=16
#PBS -o Amiga_out.txt
#PBS -e Amiga_err.txt
#PBS -V
#PBS -M cchoban@ucsd.edu
#PBS -d .
set -e

pwd

export OMP_NUM_THREADS=2
source ../module-reset.sh

pwd

# Directory of snapshots
export SNAP_DIR="/oasis/tscc/scratch/cchoban/FIRE_2_0_or_h553_criden1000_noaddm_sggs_dust/Species/output/"
# Directory to output AHF data
export OUTPUT_DIR="/oasis/tscc/scratch/cchoban/FIRE_2_0_or_h553_criden1000_noaddm_sggs_dust/Species/halos/"
# Directory of the AMIGA exe file
export AMIGA_DIR="/oasis/tscc/scratch/cchoban/FIRE_2_0_or_h553_criden1000_noaddm_sggs_dust/Species/halos/ahf/run/"
# Start and end of snapshot numbers to anaylze
export STARTNUM='590'
export ENDNUM='600'

python amigascript.py $SNAP_DIR $OUTPUT_DIR $AMIGA_DIR $STARTNUM $ENDNUM
